apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  ports:
  - name: prime-service
    port: 80
    targetPort: 9000
  selector:
    app: springboot-app
  type: NodePort
